### ISSUE TITLE
Images aren't readable/openable on Mac

### ISSUE THREAD

**Issue by ryvnnn** [ericmurphyxyz/nftgrabber#1]
Two things: 
1. It seems like there was a recent update to rarible's code where the t_preview changed to t_image_preview. Had to update that in the code. 

2. On a lot of the projects (including bayc), the files aren't readable for some reason. I try to open it up on mac but it just not readable. It has a blank preview on the desktop.

**Comment by ericmurphyxyz** [comment]
Fixed the first issue. For the second, you need an image editor that can support AVIF files, not sure which ones can for Mac but you'll have to find that out yourself
